import { Fields } from "./utils";

type Units = {
  "speed-units": string[];
  "speed-bytes": number;
  "size-units": string[];
  "size-bytes": number;
  "memory-units": string[];
  "memory-bytes": number;
};

export type Response = {
  "alt-speed-down": number;
  "alt-speed-enabled": boolean;
  "alt-speed-time-begin": number;
  "alt-speed-time-enabled": boolean;
  "alt-speed-time-end": number;
  "alt-speed-time-day": number;
  "alt-speed-up": number;
  "blocklist-url": string;
  "blocklist-enabled": boolean;
  "blocklist-size": number;
  "cache-size-mb": number;
  "config-dir": string;
  "download-dir": string;
  "download-queue-size": number;
  "download-queue-enabled": boolean;
  "dht-enabled": boolean;
  encryption: string;
  "idle-seeding-limit": number;
  "idle-seeding-limit-enabled": boolean;
  "incomplete-dir": string;
  "incomplete-dir-enabled": boolean;
  "lpd-enabled": boolean;
  "peer-limit-global": number;
  "peer-limit-per-torrent": number;
  "pex-enabled": boolean;
  "peer-port": number;
  "peer-port-random-on-start": boolean;
  "port-forwarding-enabled": boolean;
  "queue-stalled-enabled": boolean;
  "queue-stalled-minutes": number;
  "rename-partial-files": boolean;
  "rpc-version": number;
  "rpc-version-minimum": number;
  "script-torrent-done-filename": string;
  "script-torrent-done-enabled": boolean;
  seedRatioLimit: number;
  seedRatioLimited: boolean;
  "seed-queue-size": number;
  "seed-queue-enabled": boolean;
  "speed-limit-down": number;
  "speed-limit-down-enabled": boolean;
  "speed-limit-up": number;
  "speed-limit-up-enabled": boolean;
  "start-added-torrents": boolean;
  "trash-original-torrent-files": boolean;
  units: Units;
  "utp-enabled": boolean;
  version: string;
};

export type Request = Partial<Fields<keyof Response>>;
