packages:
  - packages/*

allowBuilds:
  esbuild: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - dtrace-provider

nodeLinker: hoisted

overrides:
  expo-modules-core: 3.0.30
  expo-file-system: "$expo-file-system"
  expo-router: "$expo-router"
