packages:
  - packages/*

allowBuilds:
  '@shopify/react-native-skia': true
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - dtrace-provider

nodeLinker: hoisted

overrides:
  react: "$react"
  react-native: "$react-native"
  expo-modules-core: 56.0.14
  expo-file-system: "$expo-file-system"
  expo-router: "$expo-router"
