export type {
  QBittorrentConfig,
  TorrentState,
  TorrentInfo,
  TorrentInfoParams,
  TorrentProperties,
  TorrentFile,
  TorrentTracker,
  TorrentPeer,
  TorrentPeersResponse,
  TransferInfo,
  Preferences,
  AddTorrentParams,
  TorrentFileInput,
} from "./schemas";
